Repository Shimpyo-House/Shimpyo_FE, pull requests merged in 2023-11, with the labels that each got.

#5 [#2] 초기 글로벌 스타일 설정
  src/main.tsx
  src/style/global.css
  src/style/globalStyles.ts
  src/style/theme.ts
Labels: Design

#8 [#6] Header 디자인
  package-lock.json
  package.json
  public/rabbit.jpg
  src/components/common/Header.tsx
Labels: Design

#10 [#1] 장바구니 페이지 디자인
  src/Router.tsx
  src/components/common/Header.tsx
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartTotal.tsx
  src/components/layout/cart/cartimg.png
  src/pages/Cart.tsx
  src/style/theme.ts
Labels: Design

#14 [#13] 카테고리 상품 조회 UI 생성
  src/Router.tsx
  src/components/common/Header.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/HotList.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/RowList.tsx
  src/components/layout/productsList/RowProduct.tsx
  src/components/layout/productsList/useProductsData.ts
  src/mocks/handler.ts
  src/pages/CategoryProducts.tsx
  src/pages/Home.tsx
Labels: Design

#17 [#16] 카테고리 상품 조회 msw 연결
  src/components/common/Header.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/RowList.tsx
  src/components/layout/productsList/RowProduct.tsx
  src/components/layout/productsList/useProductsData.ts
  src/mocks/handler.ts
Labels: Feat, Design

#19 [#15] 장바구니 mock data 연결
  package.json
  src/api/cart.ts
  src/components/common/Header.tsx
  src/components/layout/cart/CartItem.tsx
  src/mocks/handler.ts
  src/pages/Cart.tsx
  src/types/index.ts
Labels: Feat

#21 [#18] 헤더 메뉴버튼 클릭 시 메뉴바 생성
  src/App.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/MenuBtn.tsx
  src/components/layout/productsList/MainProductsList.tsx
Labels: Feat, Design

#22 [#9] 상품 주문하기 페이지 UI
  .eslintrc.json
  src/Router.tsx
  src/api/OrderComplete.ts
  src/components/common/header/Header.tsx
  src/components/layout/Pay/BookingInfo.tsx
  src/components/layout/Pay/BookingUser.tsx
  src/components/layout/Pay/CheckBooking.tsx
  src/components/layout/Pay/PayMethod.tsx
  src/components/layout/Pay/Payment.tsx
  src/pages/OrderedList.tsx
  src/pages/Pay.tsx
Labels: Feat, Design

#25 [#11] 로그인 / 회원가입 대략 디자인 및 기능 연결 + Axios 통신 토큰 없을 시 예외처리 추가
  docs/API_Mocking_Example.md
  package-lock.json
  package.json
  src/Axios.ts
  src/Router.tsx
  src/atoms/user.tsx
  src/components/common/AuthHeader.tsx
  src/components/layout/auth/SigninForm.tsx
  src/components/layout/auth/SignupForm.tsx
  src/components/layout/auth/auth.utils.tsx
  src/main.tsx
  src/mocks/handler.ts
  src/pages/Signin.tsx
  src/pages/Signup.tsx
  src/style/theme.ts
  src/types/index.ts
Labels: Feat, Refactor, Design

#26 [#5] 상품 상세 페이지 mock data 연결&달력 연결
  package-lock.json
  package.json
  public/img1.jpeg
  src/Router.tsx
  src/components/common/header/Header.tsx
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsDetail/ProductsRoom.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/RowList.tsx
  src/mocks/handler.ts
  src/pages/ProductDetail.tsx
  src/style/theme.ts
Labels: Feat, Design

#31 [#20] 장바구니 - 체크박스 로직 및 계산 로직 구현
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartTotal.tsx
  src/pages/Cart.tsx
Labels: Feat

#33 [#30] 상품상세페이지 - 캘린더 및 이미지 슬라이더 구현
  package-lock.json
  package.json
  public/img2.jpeg
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/mocks/handler.ts
Labels: Feat, Design

#36 [#24] 메인페이지 리액트쿼리 적용
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/RowList.tsx
  src/components/layout/productsList/RowProduct.tsx
  src/components/layout/productsList/useProductsData.ts
  src/main.tsx
  src/mocks/handler.ts
  src/pages/Home.tsx
Labels: Feat

#34 [#32] 결제 페이지 기능 추가 및 보완
  src/components/common/header/Header.tsx
  src/components/layout/Pay/BookingUser.tsx
  src/components/layout/Pay/CheckBooking.tsx
  src/components/layout/Pay/Payment.tsx
Labels: Feat

#45 [#44] 결제 수단/요청 사항 추가, 결제 페이지 로딩 추가
  public/kakaopay.png
  public/naverpay.png
  public/paypal.png
  public/tosspay.png
  src/components/common/header/MenuBtn.tsx
  src/components/layout/Pay/BookingUser.tsx
  src/components/layout/Pay/OrderedProduct.tsx
  src/components/layout/Pay/PayMethod.tsx
  src/pages/OrderedList.tsx
  src/pages/Pay.tsx
Labels: Feat, Design

#46 [#43] 장바구니 로직 추가
  src/api/cart.ts
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartTotal.tsx
  src/mocks/handler.ts
  src/pages/Cart.tsx
  src/types/index.ts
Labels: Feat

#48 [#39] 숙소상세페이지 백엔드 API 연결
  docs/API_Mocking_Example.md
  package-lock.json
  package.json
  src/components/layout/productsDetail/PeopleSelector.tsx
  src/components/layout/productsDetail/ProductDetailImgSlider.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/RowProduct.tsx
  src/hooks/useProductsData.ts
  src/mocks/handler.ts
  src/pages/Home.tsx
Labels: Feat

#50 [#49] 예약 내역 페이지 생성
  src/Router.tsx
  src/components/layout/Pay/AllReservation.tsx
  src/pages/MyReservation.tsx
Labels: Design

#55 [#47] 장바구니 - 예약 검사 및 선점 로직 구성 및 Recoil 전역 변수에 장바구니 주문 데이터 담기
  src/api/cart.ts
  src/atoms/cartAtom.ts
  src/components/layout/cart/CartTotal.tsx
  src/mocks/handler.ts
  src/types/index.ts
Labels: Feat

#56 [#53] 카테고리 페이지 무한스크롤
  src/components/common/header/MenuBtn.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/hooks/useProductsData.ts
  src/types/index.ts
Labels: Feat

#57 [#39] 숙소상세페이지 로직 완료 및 장바구니 API 연결
  package-lock.json
  package.json
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
Labels: Fix, Feat

#60 [#54] 장바구니 DELETE API 연결
  src/api/cart.ts
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartNoItem.tsx
  src/hooks/useCart.ts
  src/mocks/handler.ts
  src/pages/Cart.tsx
  src/style/globalStyles.ts
Labels: Feat, Design

#63 [#58] 예약 가능 여부 체크
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/PeopleSelector.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
Labels: Feat, Design

#66 [#59]메인페이지, 카테고리 페이지 디자인 수정
  src/App.tsx
  src/components/common/header/MenuBtn.tsx
  src/components/layout/auth/MyPageForm.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/ListBackground.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/RowProduct.tsx
  src/hooks/useProductsData.ts
  src/pages/CategoryProducts.tsx
  src/pages/Home.tsx
Labels: Chore, Design

#67 [#64] 숙소상세페이지 디자인작업
  package-lock.json
  package.json
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/types/index.ts
Labels: Feat, Design

#70 [#51] 백엔드 데이터 연결
  package-lock.json
  package.json
  src/Axios.ts
  src/api/OrderComplete.ts
  src/components/common/Loading.tsx
  src/components/common/header/MenuBtn.tsx
  src/components/layout/Pay/AllReservation.tsx
  src/components/layout/Pay/BookingInfo.tsx
  src/components/layout/Pay/CheckBooking.tsx
  src/components/layout/Pay/OrderedProduct.tsx
  src/components/layout/Pay/PayMethod.tsx
  src/components/layout/Pay/Payment.tsx
  src/pages/MyReservation.tsx
  src/pages/OrderedList.tsx
  src/types/index.ts
Labels: Fix, Feat

#73 [#64] 숙소상세페이지 디자인 작업
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/types/index.ts
Labels: Feat, Design

#77 [#64 ]숙소상세페이지 예약하기 post 연결
  src/components/common/header/Header.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/types/index.ts
Labels: Feat

#81 [#72] 알럿창 swal로 변경
  package-lock.json
  package.json
  src/PrivateRoute.tsx
  src/api/cart.ts
  src/components/common/header/MenuBtn.tsx
  src/components/layout/Pay/Payment.tsx
  src/components/layout/auth/MyPageForm.tsx
  src/components/layout/auth/SigninForm.tsx
  src/components/layout/auth/SignupForm.tsx
  src/components/layout/cart/CartTotal.tsx
  src/hooks/useTokenRefresher.ts
Labels: Feat

#86 [#80] 장바구니 리팩토링
  src/components/common/header/Header.tsx
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartTotal.tsx
  src/components/layout/cart/cartimg.png
  src/types/index.ts
Labels: Refactor

#89 [Refactor] 장바구니 리팩토링
  src/api/cart.ts
  src/components/common/header/Header.tsx
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartTotal.tsx
  src/components/layout/cart/cartimg.png
  src/types/index.ts
Labels: Refactor

#93 [#83] 카테고리 페이지, 검색 페이지, 검색창 UI 수정
  src/components/common/header/Header.tsx
  src/components/common/header/searchBar/SearchBar.tsx
  src/components/common/header/searchBar/SearchOptions.tsx
  src/components/common/header/searchBar/SelectBox.tsx
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/RowProduct.tsx
  src/components/layout/productsList/SearchProductsList.tsx
  src/hooks/useProductsData.ts
  src/pages/Home.tsx
Labels: Design
