Repository Shimpyo-House/Shimpyo_FE, pull requests merged in 2023-12, with the labels that each got.

#103 [#64] 숙소상세페이지 디자인 작업
  .vscode/settings.json
  index.html
  netlify 2.toml
  package-lock.json
  package.json
  public/img1.jpeg
  public/img2.jpeg
  public/mockServiceWorker.js
  public/rabbit.jpg
  public/vite.svg
  src/components/layout/cart/CartItem.tsx
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ImageSlider.tsx
  src/components/layout/productsDetail/Location.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsDetail/ProductsRoom.tsx
Labels: Feat

#104 [#102] 장바구니 컴포넌트 분리
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartOrder.tsx
  src/components/layout/cart/CartTotal.tsx
Labels: Refactor

#106 [#99] 검색 시 새로고침 상태변화로 대체
  src/api/productsList.ts
  src/components/common/header/Header.tsx
  src/components/common/header/searchBar/SearchBar.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/SearchProductsList.tsx
  src/hooks/useObs.ts
  src/pages/Home.tsx
  src/pages/SearchProducts.tsx
Labels: Refactor

#112 [#108] 카테고리 페이지, 검색 페이지 숙소 디자인 변경
  src/api/productsList.ts
  src/components/common/header/searchBar/SearchBar.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnList.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/components/layout/productsList/SearchProduct.tsx
  src/components/layout/productsList/SearchProductsList.tsx
  src/hooks/useObs.ts
  src/pages/Home.tsx
  src/types/index.ts
Labels: Fix, Refactor, Design

#113 [#64] 숙소상세페이지 디자인 작업
  index.html
  netlify 2.toml
  package-lock.json
  package.json
  public/img1.jpeg
  public/img2.jpeg
  public/mockServiceWorker.js
  public/rabbit.jpg
  public/vite.svg
  src/api/productsList.ts
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ImageSlider.tsx
  src/components/layout/productsDetail/Location.tsx
  src/components/layout/productsDetail/LocationWithCustomOverlay.tsx
  src/components/layout/productsDetail/PeopleSelector.tsx
  src/components/layout/productsDetail/ProductsDetail.test.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsList/ColumnList 2.tsx
  src/components/layout/productsList/SearchProductsList.tsx
  src/pages/MyReservation.tsx
  src/types/index.ts
Labels: Feat, Refactor, Design

#118 [#114] 숙소상세페이지 추가작업
  src/atoms/cartAtom.ts
  src/components/common/AuthHeader.tsx
  src/components/layout/Pay/BookingInfo.tsx
  src/components/layout/Pay/OrderedProduct.tsx
  src/components/layout/Pay/Payment.tsx
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartOrder.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/pages/OrderedList.tsx
  src/types/index.ts
Labels: Feat, Design

#120 [#116] 상세 페이지 - 룸 상세 정보 모달 추가
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsDetail/RoomOptionModal.tsx
Labels: Feat

#129 [#115] 장바구니 API 수정
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartOrder.tsx
  src/types/index.ts
Labels: Fix

#130 [#120] 숙소상페이지 작업
  src/api/cart.ts
  src/components/layout/productsDetail/LocationWithCustomOverlay.tsx
  src/components/layout/productsDetail/ProductAmenities.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsList/ColumnList 2.tsx
  src/pages/ProductDetail.tsx
Labels: Feat, Design

#132 [#122] 숙소상세페이지 추가작업
  src/components/layout/productsDetail/ProductAmenities.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/types/index.ts
Labels: Fix, Feat, Design

#133 [#122] 숙소상세페이지 수정
  src/components/layout/productsDetail/ProductAmenities.tsx
  src/components/layout/productsDetail/RoomOptionModal.tsx
Labels: Design

#134 [#125] 결제 완료/예약내역확인 페이지 API data 변경
  .eslintrc.json
  src/api/OrderList.ts
  src/atoms/cartAtom.ts
  src/components/layout/Pay/AllReservation.tsx
  src/components/layout/Pay/BookingInfo.tsx
  src/components/layout/Pay/BookingUser.tsx
  src/components/layout/Pay/CheckBooking.tsx
  src/components/layout/Pay/OrderedProduct.tsx
  src/components/layout/Pay/Payment.tsx
  src/pages/MyReservation.tsx
  src/pages/OrderedList.tsx
  src/pages/Pay.tsx
  src/types/index.ts
Labels: Fix, Feat, Refactor

#137 [#122] 숙소상세페이지 수정
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ImageSlider.tsx
  src/components/layout/productsDetail/ProductsDetail.test.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsDetail/RoomOptionModal.tsx
Labels: Chore, Design

#141 [#140] 결제 페이지 유효성 수정
  .eslintrc.json
  src/components/layout/Pay/AllReservation.tsx
  src/components/layout/Pay/BookingInfo.tsx
  src/components/layout/Pay/OrderedProduct.tsx
  src/components/layout/Pay/Payment.tsx
Labels: Fix

#142 [#131] 장바구니 API 변경으로 인한 로직 수정
  src/api/cart.ts
  src/atoms/cartAtom.ts
  src/components/layout/cart/CartItem.tsx
  src/components/layout/cart/CartNoItem.tsx
  src/components/layout/cart/CartOrder.tsx
  src/types/index.ts
Labels: Fix

#144 [#143] 이중 map 제거
  src/components/layout/Pay/BookingInfo.tsx
  src/components/layout/Pay/OrderedProduct.tsx
  src/components/layout/Pay/Payment.tsx
Labels: Fix

#149 [#146] 장수빈 README 작성
  README.md
  src/components/layout/cart/CartItem.tsx
Labels: Chore

#153 [#152] 전체 파일 불필요한 주석 및 코드 제거
  README.md
  src/api/OrderList.ts
  src/api/favorite.ts
  src/api/productsList.ts
  src/atoms/loading.ts
  src/atoms/user.ts
  src/components/common/AuthHeader.tsx
  src/components/common/header/searchBar/SearchBar.tsx
  src/components/layout/Pay/BookingInfo.tsx
  src/components/layout/Pay/CheckBooking.tsx
  src/components/layout/auth/MyPageForm.tsx
  src/components/layout/auth/SigninForm.tsx
  src/components/layout/auth/SignupForm.tsx
  src/components/layout/productsDetail/Calendar.tsx
  src/components/layout/productsDetail/ImageSlider.tsx
  src/components/layout/productsDetail/LocationWithCustomOverlay.tsx
  src/components/layout/productsDetail/ProductAmenities.tsx
  src/components/layout/productsDetail/ProductDetailImgSlider.tsx
  src/components/layout/productsDetail/ProductsDetail.tsx
  src/components/layout/productsDetail/RoomImageSlider.tsx
  src/components/layout/productsDetail/RoomOptionModal.tsx
  src/components/layout/productsList/CategoryProductsList.tsx
  src/components/layout/productsList/ColumnList.tsx
  src/components/layout/productsList/ColumnProduct.tsx
  src/components/layout/productsList/MainProductsList.tsx
  src/hooks/changeProductData.ts
  src/hooks/useTokenRefresher.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handler.ts
  src/pages/Home.tsx
  src/pages/OrderedList.tsx
  src/pages/ProductDetail.tsx
Labels: Refactor
